
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - "pypy"
  - "pypy3"
install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install --upgrade autopep8
  - pip install statistics
  - pip install matplotlib
  - pip install numpy
# install:
#   - pip install ".[test]" . # install package + test dependencies
script: pytest
after_success:
  - codecov # submit coverage